### ISSUE TITLE
`npm install` fails

### ISSUE THREAD

**Issue by wsergio** [voidlabs/mosaico#10]
Hey,

So I was trying to get up and running mosaico on CentOS 7.
Long story short, `npm install` fails with:
```bash
Stack trace:
Error: Error (1): npm install --production in bower_components/knockout
    at ChildProcess.<anonymous> (/home/web/apps/mosaico/node_modules/bower-npm-install/lib/install.js:137:57)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)

Console trace:
Error
    at StandardRenderer.error (/home/web/apps/mosaico/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/home/web/apps/mosaico/node_modules/bower-npm-install/lib/coa.js:71:26)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/home/web/apps/mosaico/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at _rejected (/home/web/apps/mosaico/node_modules/bower-npm-install/node_modules/q/q.js:808:24)
    at /home/web/apps/mosaico/node_modules/bower-npm-install/node_modules/q/q.js:834:30
    at Promise.when (/home/web/apps/mosaico/node_modules/bower-npm-install/node_modules/q/q.js:1079:31)
    at Promise.promise.promiseDispatch (/home/web/apps/mosaico/node_modules/bower-npm-install/node_modules/q/q.js:752:41)
    at /home/web/apps/mosaico/node_modules/bower-npm-install/node_modules/q/q.js:574:44
    at flush (/home/web/apps/mosaico/node_modules/bower-npm-install/node_modules/q/q.js:108:17)
System info:
Bower version: 1.4.1
Node version: 0.10.40
OS: Linux 3.10.0-123.8.1.el7.x86_64 x64
Error: Error (1): npm install --production in bower_components/knockout
    at ChildProcess.<anonymous> (/home/web/apps/mosaico/node_modules/bower-npm-install/lib/install.js:137:57)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)

npm ERR! mosaico@0.10.0 postinstall: `bower-npm-install --non-interactive`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mosaico@0.10.0 postinstall script.
npm ERR! This is most likely a problem with the mosaico package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower-npm-install --non-interactive
npm ERR! You can get their info via:
npm ERR!     npm owner ls mosaico
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.10.0-123.8.1.el7.x86_64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/web/apps/mosaico
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/web/apps/mosaico/npm-debug.log
npm ERR! not ok code 0
```
The full output: http://pastebin.com/mPW8ixXw
The partial npm-debug.log: http://pastebin.com/F9bVtjDp

Any ideas what the issue might be?

Thanks!

PS: the demo looks promising, good job! :+1:

**Comment by bago** [comment]
I often see similar errors in npm install: try repeating it a few times, it will probably break a bit later until it reaches the end, let me know!

**Comment by wsergio** [comment]
Indeed. It failed a few more times, but, in the end, I could successfully run `grunt` and access the demo at `http://127.0.0.1:9000`.

One of the errors was quite weird:
( more output: http://pastebin.com/yjQtajeN )
```bash
Console trace:
Error
    at StandardRenderer.error (/home/vagrant/mosaico/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/home/vagrant/mosaico/node_modules/bower-npm-install/lib/coa.js:71:26)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/home/vagrant/mosaico/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at _rejected (/home/vagrant/mosaico/node_modules/bower-npm-install/node_modules/q/q.js:808:24)
    at /home/vagrant/mosaico/node_modules/bower-npm-install/node_modules/q/q.js:834:30
    at Promise.when (/home/vagrant/mosaico/node_modules/bower-npm-install/node_modules/q/q.js:1079:31)
    at Promise.promise.promiseDispatch (/home/vagrant/mosaico/node_modules/bower-npm-install/node_modules/q/q.js:752:41)
    at /home/vagrant/mosaico/node_modules/bower-npm-install/node_modules/q/q.js:574:44
    at flush (/home/vagrant/mosaico/node_modules/bower-npm-install/node_modules/q/q.js:108:17)
System info:
Bower version: 1.4.1
Node version: 0.10.36
OS: Linux 3.10.0-229.11.1.el7.x86_64 x64
Error: Error (1): npm install --production in bower_components/evol-colorpicker
    at ChildProcess.<anonymous> (/home/vagrant/mosaico/node_modules/bower-npm-install/lib/install.js:137:57)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
**npm ERR! weird error 1
npm ERR! not ok code 0**
```
