### ISSUE TITLE
npm installation failure

### ISSUE THREAD

**Issue by aermicioi** [voidlabs/mosaico#168]
Installation of mosaico dependencies fails with npm install command on:
Debian sid, nodejs v4.4.6, npm v1.4.21
with global npm packages:
bower@1.7.9
cordova@6.2.0
grunt-cli@1.2.0
gulp@3.9.1
ionic@1.7.16
jspm@0.16.39
nodemon@1.9.2

For release 0.14 of mosaico.
Errors encountered on first attempt to install (it is encountered as well on update command):
```
npm ERR! cb() never called!
npm ERR! not ok code 0
```
On second install another error appears:
```
sh: 1: bower-npm-install: not found

npm ERR! mosaico@0.14.0 postinstall: `bower-npm-install --non-interactive`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the mosaico@0.14.0 postinstall script.
npm ERR! This is most likely a problem with the mosaico package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower-npm-install --non-interactive
npm ERR! You can get their info via:
npm ERR!     npm owner ls mosaico
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.6.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd ~/Workspace/js/mosaico
npm ERR! node -v v4.4.6
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     ~/Workspace/js/mosaico/npm-debug.log
npm ERR! not ok code 0
```

I think it can't find binary for bower-npm-install, because it is installed locally, and not globally, installing it globally fixes second error message (since directory of local install is not on PATH variable).

On new clean attempt with bower installed globally we still get the first error on install. On second attempt to run npm install, we get another one:
```
bower knockout#3.4.0                                                   npm install Warning: Cannot find module 'closure-compiler' Use --force to continue.
bower knockout#3.4.0                                                   npm install Aborted due to warnings.
bower knockout#3.4.0                                                   npm install npm ERR! knockout@3.4.0 prepublish: `grunt`
bower knockout#3.4.0                                                   npm install npm ERR! Exit status 3
bower knockout#3.4.0                                                   npm install npm ERR! 
bower knockout#3.4.0                                                   npm install npm ERR! Failed at the knockout@3.4.0 prepublish script.
bower knockout#3.4.0                                                   npm install npm ERR! This is most likely a problem with the knockout package,
bower knockout#3.4.0                                                   npm install npm ERR! not with npm itself.
bower knockout#3.4.0                                                   npm install npm ERR! Tell the author that this fails on your system:
bower knockout#3.4.0                                                   npm install npm ERR!     grunt
bower knockout#3.4.0                                                   npm install npm ERR! You can get their info via:
bower knockout#3.4.0                                                   npm install npm ERR!     npm owner ls knockout
bower knockout#3.4.0                                                   npm install npm ERR! There is likely additional logging output above.
bower knockout#3.4.0                                                   npm install npm ERR! System Linux 4.6.0-1-amd64
bower knockout#3.4.0                                                   npm install npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--production"
bower knockout#3.4.0                                                   npm install npm ERR! cwd ~/Workspace/js/mosaico/bower_components/knockout
bower knockout#3.4.0                                                   npm install npm ERR! node -v v4.4.6
bower knockout#3.4.0                                                   npm install npm ERR! npm -v 1.4.21
bower knockout#3.4.0                                                   npm install npm ERR! code ELIFECYCLE
bower knockout#3.4.0                                                   npm install npm WARN This failure might be due to the use of legacy binary "node"
bower knockout#3.4.0                                                   npm install npm WARN For further explanations, please read
bower knockout#3.4.0                                                   npm install /usr/share/doc/nodejs/README.Debian
bower knockout#3.4.0                                                   npm install  
bower knockout#3.4.0                                                   npm install npm ERR! 
bower knockout#3.4.0                                                   npm install npm ERR! Additional logging details can be found in:
bower knockout#3.4.0                                                   npm install npm ERR!     ~/Workspace/js/mosaico/bower_components/knockout/npm-debug.log
bower knockout#3.4.0                                                   npm install npm ERR! not ok code 0
bower                                                                        error Error (1): npm install --production in bower_components/knockout

Stack trace:
Error: Error (1): npm install --production in bower_components/knockout
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/bower-npm-install/lib/install.js:137:57)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower-npm-install/lib/coa.js:71:26)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (/usr/local/lib/node_modules/bower-npm-install/node_modules/bower-logger/lib/Logger.js:29:39)
    at _rejected (/usr/local/lib/node_modules/bower-npm-install/node_modules/q/q.js:844:24)
    at /usr/local/lib/node_modules/bower-npm-install/node_modules/q/q.js:870:30
    at Promise.when (/usr/local/lib/node_modules/bower-npm-install/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower-npm-install/node_modules/q/q.js:788:41)
    at /usr/local/lib/node_modules/bower-npm-install/node_modules/q/q.js:604:44
System info:
Bower version: 1.7.9
Node version: 4.4.6
OS: Linux 4.6.0-1-amd64 x64
(node) util.error is deprecated. Use console.error instead.
Error: Error (1): npm install --production in bower_components/knockout
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/bower-npm-install/lib/install.js:137:57)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

npm ERR! mosaico@0.14.0 postinstall: `bower-npm-install --non-interactive`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mosaico@0.14.0 postinstall script.
npm ERR! This is most likely a problem with the mosaico package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower-npm-install --non-interactive
npm ERR! You can get their info via:
npm ERR!     npm owner ls mosaico
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.6.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd ~/Workspace/js/mosaico
npm ERR! node -v v4.4.6
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     ~/Workspace/js/mosaico/npm-debug.log
npm ERR! not ok code 0
```
Hoping that installation problems will be fixed.
Thank you.

**Comment by bago** [comment]
npm cache clean
npm install (multiple times if you get differnt errors, stop if same error)
npm update (multiple times if you get differnt errors, stop if same error)

if "npm update" still keeps throwing the same error paste it. Otherwise if it works, start grunt and paste its error.

Repeat this whole process twice to confirm you stuck in the same "place" with the same error both times.

**Comment by aermicioi** [comment]
### For 0.14 release, as instructed on clean copy installation process:
I have run, npm cache clean, and npm install after some list of installing packages got:
```
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN engine punycode@2.0.0: wanted: {"node":">=6"} (current: {"node":"4.4.6","npm":"1.4.21"})
npm WARN engine punycode@2.0.0: wanted: {"node":">=6"} (current: {"node":"4.4.6","npm":"1.4.21"})
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm ERR! cb() never called!
npm ERR! not ok code 0
```
After npm install, I issued a npm update command which was updating packages and at some point got:
```
debowerify@1.2.0 node_modules/debowerify
├── ordered-ast-traverse@0.1.1 (ordered-esprima-props@1.0.0)
├── esprima@1.2.5
├── through@2.3.8
└── bower@1.3.12 (is-root@1.0.0, abbrev@1.0.9, junk@1.0.3, stringify-object@1.0.1, which@1.0.9, chmodr@0.1.0, opn@1.0.2, osenv@0.1.0, q@1.0.1, bower-endpoint-parser@0.2.2, bower-logger@0.2.2, archy@0.0.2, lockfile@1.0.1, nopt@3.0.6, rimraf@2.2.8, graceful-fs@3.0.8, lru-cache@2.5.2, retry@0.6.0, tmp@0.0.23, semver@2.3.2, p-throttler@0.1.0, shell-quote@1.4.3, request-progress@0.3.0, chalk@0.5.0, bower-json@0.4.0, promptly@0.2.0, mkdirp@0.5.0, bower-config@0.5.2, cardinal@0.4.0, request@2.42.0, decompress-zip@0.0.8, bower-registry-client@0.2.4, fstream@1.0.10, update-notifier@0.2.0, fstream-ignore@1.0.5, glob@4.0.6, handlebars@2.0.0, tar-fs@0.5.2, mout@0.9.1, inquirer@0.7.1, insight@0.4.3)
npm ERR! cb() never called!
npm ERR! not ok code 0

```
Again run npm cache clean, and npm install got:
```
> mosaico@0.14.0 postinstall /home/aermicioi/Workspace/js/mosaico
> bower-npm-install --non-interactive

sh: 1: bower-npm-install: not found

npm ERR! mosaico@0.14.0 postinstall: `bower-npm-install --non-interactive`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the mosaico@0.14.0 postinstall script.
npm ERR! This is most likely a problem with the mosaico package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower-npm-install --non-interactive
npm ERR! You can get their info via:
npm ERR!     npm owner ls mosaico
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.6.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/aermicioi/Workspace/js/mosaico
npm ERR! node -v v4.4.6
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/aermicioi/Workspace/js/mosaico/npm-debug.log
npm ERR! not ok code 0
```
Runned npm update and got same error:
```
debowerify@1.2.0 node_modules/debowerify
├── esprima@1.2.5
├── ordered-ast-traverse@0.1.1 (ordered-esprima-props@1.0.0)
├── through@2.3.8
└── bower@1.3.12 (is-root@1.0.0, abbrev@1.0.9, junk@1.0.3, stringify-object@1.0.1, which@1.0.9, chmodr@0.1.0, opn@1.0.2, osenv@0.1.0, q@1.0.1, bower-endpoint-parser@0.2.2, bower-logger@0.2.2, lockfile@1.0.1, archy@0.0.2, nopt@3.0.6, rimraf@2.2.8, lru-cache@2.5.2, graceful-fs@3.0.8, retry@0.6.0, tmp@0.0.23, p-throttler@0.1.0, request-progress@0.3.0, semver@2.3.2, shell-quote@1.4.3, chalk@0.5.0, bower-json@0.4.0, promptly@0.2.0, fstream-ignore@1.0.5, fstream@1.0.10, mkdirp@0.5.0, glob@4.0.6, bower-config@0.5.2, cardinal@0.4.0, bower-registry-client@0.2.4, decompress-zip@0.0.8, request@2.42.0, tar-fs@0.5.2, update-notifier@0.2.0, handlebars@2.0.0, mout@0.9.1, inquirer@0.7.1, insight@0.4.3)
npm ERR! cb() never called!
npm ERR! not ok code 0
```
Runned third time npm cache clean, and install. Ended up in same error:
```
> mosaico@0.14.0 postinstall /home/aermicioi/Workspace/js/mosaico
> bower-npm-install --non-interactive

sh: 1: bower-npm-install: not found

npm ERR! mosaico@0.14.0 postinstall: `bower-npm-install --non-interactive`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the mosaico@0.14.0 postinstall script.
npm ERR! This is most likely a problem with the mosaico package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower-npm-install --non-interactive
npm ERR! You can get their info via:
npm ERR!     npm owner ls mosaico
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.6.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/aermicioi/Workspace/js/mosaico
npm ERR! node -v v4.4.6
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/aermicioi/Workspace/js/mosaico/npm-debug.log
npm ERR! not ok code 0
```

So at the end both commands end with repeatable errors.

### Notes:
For npm install and error with bower-npm-install it is possible to fix by installing it globally. As I mentioned this error can occur due to the fact that, the npm can not find local installation of binary, and fails to invoke it.
Even after fixing the not found binary, other problem occurs with bower installing knockout#3.4.0, should I post the error as well?

Thank you.

**Comment by bago** [comment]
Did you even install other npm applications on your machine? It seems you have very generic  issues and they don't seems to be related to mosaico (cb() never called) happening in various steps.

Travis is able to install/build/test mosaico on many node versions:
https://travis-ci.org/voidlabs/mosaico

**Comment by aermicioi** [comment]
Not sure why, but updating node package from v4.4.6 to v4.4.7 fixed error with cb() never called. 
Hope that node will make more sane errors than "cb() never called".

Thank you for help.
