### ISSUE TITLE
spawn convert ENOENT

### ISSUE THREAD

**Issue by jmosawy** [voidlabs/mosaico#290]
Hi,

I'm running Mosaico on my machine and everything works well, but running it on the server fails. The following error appears on terminal when I upload an image when building a template.
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn convert ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Any solution?

**Comment by bago** [comment]
I run it on "the server" and it works. Most of us run it on "the server" without issues...

Don't you think that detailing what "the server" is would help? OS, node version, the exact build/run procedure you use...

https://github.com/voidlabs/mosaico/blob/master/CONTRIBUTING.md

**Comment by brentdur** [comment]
Make sure imageMagick is installed on "the server"

**Comment by bago** [comment]
16 days since I asked for details. Closing.
