### ISSUE TITLE
Test failed

### ISSUE THREAD

**Issue by blsn** [voidlabs/mosaico#296]
I cloned the repository: `git clone https://github.com/voidlabs/mosaico.git`
I'm getting the error below while trying to perform the test:

```
vagrant@homestead:~/sites/mscv01/mosaico$ npm --version
3.10.10
vagrant@homestead:~/sites/mscv01/mosaico$ node --version
v6.10.0
vagrant@homestead:~/sites/mscv01/mosaico$
vagrant@homestead:~/sites/mscv01/mosaico$ sudo npm install -g grunt-cli
/usr/bin/grunt -> /usr/lib/node_modules/grunt-cli/bin/grunt
/usr/lib
└── grunt-cli@1.2.0

vagrant@homestead:~/sites/mscv01/mosaico$ sudo npm install
npm WARN lifecycle mosaico@0.16.0~postinstall: cannot run in wd %s %s (wd=%s) mosaico@0.16.0 ./node_modules/bower-npm-install/bin/bower-npm-install --non-interactive /home/vagrant/sites/mscv01/mosaico
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
vagrant@homestead:~/sites/mscv01/mosaico$ sudo npm test

> mosaico@0.16.0 test /home/vagrant/sites/mscv01/mosaico
> grunt jasmine_node

Running "jasmine_node:main" (jasmine_node) task
WARNING: loading non-allowed module: cheerio
WARNING: loading non-allowed module: ./lib/cheerio
WARNING: loading non-allowed module: ./parse
WARNING: loading non-allowed module: htmlparser2
WARNING: loading non-allowed module: ./Parser.js
WARNING: loading non-allowed module: ./Tokenizer.js
WARNING: loading non-allowed module: entities/lib/decode_codepoint.js
WARNING: loading non-allowed module: ../maps/decode.json
WARNING: loading non-allowed module: entities/maps/entities.json
WARNING: loading non-allowed module: entities/maps/legacy.json
WARNING: loading non-allowed module: entities/maps/xml.json
WARNING: loading non-allowed module: inherits
WARNING: loading non-allowed module: events
WARNING: loading non-allowed module: domhandler
WARNING: loading non-allowed module: ./Tokenizer.js
WARNING: loading non-allowed module: domelementtype
WARNING: loading non-allowed module: ./utils
WARNING: loading non-allowed module: ./parse
WARNING: loading non-allowed module: dom-serializer
WARNING: loading non-allowed module: domelementtype
WARNING: loading non-allowed module: entities
WARNING: loading non-allowed module: ./lib/encode.js
WARNING: loading non-allowed module: ../maps/xml.json
WARNING: loading non-allowed module: ../maps/entities.json
WARNING: loading non-allowed module: ./lib/decode.js
WARNING: loading non-allowed module: ../maps/entities.json
WARNING: loading non-allowed module: ../maps/legacy.json
WARNING: loading non-allowed module: ../maps/xml.json
WARNING: loading non-allowed module: ./decode_codepoint.js
WARNING: loading non-allowed module: lodash.assignin
WARNING: loading non-allowed module: lodash.bind
WARNING: loading non-allowed module: lodash.foreach
WARNING: loading non-allowed module: lodash.defaults
WARNING: loading non-allowed module: ./api/attributes
WARNING: loading non-allowed module: ../static
WARNING: loading non-allowed module: dom-serializer
WARNING: loading non-allowed module: css-select
WARNING: loading non-allowed module: ./lib/pseudos.js
WARNING: loading non-allowed module: domutils
WARNING: loading non-allowed module: ./lib/stringify
WARNING: loading non-allowed module: domelementtype
WARNING: loading non-allowed module: dom-serializer
WARNING: loading non-allowed module: ./lib/traversal
WARNING: loading non-allowed module: ./lib/manipulation
WARNING: loading non-allowed module: ./lib/querying
WARNING: loading non-allowed module: domelementtype
WARNING: loading non-allowed module: ./lib/legacy
WARNING: loading non-allowed module: domelementtype
WARNING: loading non-allowed module: ./lib/helpers
WARNING: loading non-allowed module: nth-check
WARNING: loading non-allowed module: ./parse.js
WARNING: loading non-allowed module: ./compile.js
WARNING: loading non-allowed module: boolbase
WARNING: loading non-allowed module: ./attributes.js
WARNING: loading non-allowed module: domutils
WARNING: loading non-allowed module: boolbase
WARNING: loading non-allowed module: boolbase
WARNING: loading non-allowed module: domutils
WARNING: loading non-allowed module: boolbase
WARNING: loading non-allowed module: ./lib/compile.js
WARNING: loading non-allowed module: css-what
WARNING: loading non-allowed module: domutils
WARNING: loading non-allowed module: ./general.js
WARNING: loading non-allowed module: domutils
WARNING: loading non-allowed module: ./attributes.js
WARNING: loading non-allowed module: ./pseudos.js
WARNING: loading non-allowed module: ./sort.js
WARNING: loading non-allowed module: ./procedure.json
WARNING: loading non-allowed module: boolbase
WARNING: loading non-allowed module: ./procedure.json
WARNING: loading non-allowed module: ./pseudos.js
WARNING: loading non-allowed module: ./parse
WARNING: loading non-allowed module: lodash.merge
WARNING: loading non-allowed module: lodash.defaults
WARNING: loading non-allowed module: ../utils
WARNING: loading non-allowed module: lodash.foreach
WARNING: loading non-allowed module: lodash.assignin
WARNING: loading non-allowed module: lodash.some
WARNING: loading non-allowed module: ./api/traversing
WARNING: loading non-allowed module: css-select
WARNING: loading non-allowed module: ../utils
WARNING: loading non-allowed module: htmlparser2
WARNING: loading non-allowed module: domutils
WARNING: loading non-allowed module: lodash.bind
WARNING: loading non-allowed module: lodash.foreach
WARNING: loading non-allowed module: lodash.reject
WARNING: loading non-allowed module: lodash.filter
WARNING: loading non-allowed module: lodash.reduce
WARNING: loading non-allowed module: ./api/manipulation
WARNING: loading non-allowed module: ../parse
WARNING: loading non-allowed module: ../static
WARNING: loading non-allowed module: ../utils
WARNING: loading non-allowed module: lodash.flatten
WARNING: loading non-allowed module: lodash.bind
WARNING: loading non-allowed module: lodash.foreach
WARNING: loading non-allowed module: ./api/css
WARNING: loading non-allowed module: ../utils
WARNING: loading non-allowed module: lodash.pick
WARNING: loading non-allowed module: ./api/forms
WARNING: loading non-allowed module: lodash.map
WARNING: loading non-allowed module: ./static
WARNING: loading non-allowed module: ./package.json
WARNING: loading non-allowed module: ../bower_components/jsep/src/jsep.js
>> Jasmine runner failed: Error: Cannot find module '../bower_components/jsep/src/jsep.js'
>>   at Function.Module._resolveFilename (module.js:469:15)
>>   at Module._load (module.js:417:25)
>>   at Function.hookedLoader [as _load] (/home/vagrant/sites/mscv01/mosaico/node_modules/mockery/mockery.js:111:12)
>>   at Module.require (module.js:497:17)
>>   at require (internal/module.js:20:19)
>>   at Object.<anonymous> (/home/vagrant/sites/mscv01/mosaico/spec/converter-spec.js:20:30)
>>   at Module._compile (module.js:570:32)
>>   at Object.Module._extensions..js (module.js:579:10)
>>   at Object.Module._extensions.(anonymous function) [as .js] (/home/vagrant/sites/mscv01/mosaico/node_modules/istanbul/lib/hook.js:109:37)
>>   at Module.load (/home/vagrant/sites/mscv01/mosaico/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
>>   at tryModuleLoad (module.js:446:12)
>>   at Function.Module._load (module.js:438:3)
>>   at Module.require (module.js:497:17)
>>   at require (internal/module.js:20:19)
>>   at /home/vagrant/sites/mscv01/mosaico/node_modules/jasmine/lib/jasmine.js:87:5
>>   at Array.forEach (native)
>>   at Jasmine.loadSpecs (/home/vagrant/sites/mscv01/mosaico/node_modules/jasmine/lib/jasmine.js:86:18)
>>   at Jasmine.execute (/home/vagrant/sites/mscv01/mosaico/node_modules/jasmine/lib/jasmine.js:181:8)
>>   at runner (/home/vagrant/sites/mscv01/mosaico/node_modules/grunt-jasmine-node-coverage/tasks/jasmine-node-task.js:211:15)
>>   at matcherCallback (/home/vagrant/sites/mscv01/mosaico/node_modules/grunt-jasmine-node-coverage/tasks/jasmine-node-task.js:260:7)
>>   at /home/vagrant/sites/mscv01/mosaico/node_modules/istanbul/lib/util/file-matcher.js:68:16
>>   at /home/vagrant/sites/mscv01/mosaico/node_modules/istanbul/node_modules/async/lib/async.js:52:16
>>   at /home/vagrant/sites/mscv01/mosaico/node_modules/istanbul/node_modules/async/lib/async.js:361:13
>>   at /home/vagrant/sites/mscv01/mosaico/node_modules/istanbul/node_modules/async/lib/async.js:52:16
>>   at done (/home/vagrant/sites/mscv01/mosaico/node_modules/istanbul/node_modules/async/lib/async.js:246:17)
>>   at /home/vagrant/sites/mscv01/mosaico/node_modules/istanbul/node_modules/async/lib/async.js:44:16
>>   at /home/vagrant/sites/mscv01/mosaico/node_modules/istanbul/node_modules/async/lib/async.js:358:17
>>   at LOOP (fs.js:1759:14)
>>   at _combinedTickCallback (internal/process/next_tick.js:67:7)
>>   at process._tickCallback (internal/process/next_tick.js:98:9)
Warning: Cannot find module '../bower_components/jsep/src/jsep.js' Use --force to continue.

Aborted due to warnings.
npm ERR! Test failed.  See above for more details.
vagrant@homestead:~/sites/mscv01/mosaico$

```

**Comment by bago** [comment]
Please try to change the "scripts" section of the package.json to:
```
  "scripts": {
    "postinstall": "bower -V --allow-root install",
    "deps": "bower -V --allow-root install",
    "test": "grunt jasmine_node"
  },
```

Let me know if this fixes your issue.

**Comment by blsn** [comment]
Thank you for your reply.
I already solved it by installing Nodejs & Npm again (I used node.js PPA).

```
34 specs, 0 failures
Finished in 3.335 seconds
Executed 34 of 34 specs SUCCESS in 3 secs.

```
