### ISSUE TITLE
Cannot send test e-mails

### ISSUE THREAD

**Issue by Freelensia** [voidlabs/mosaico#334]
Hi,

Please bare with me as I am a beginner in coding and have no knowledge of node.js. I use Windows 10. I have successfully installed run the off-line version of the Mosaico yesterday (node.js, grunt, imagemagik, git are all properly installed as per the instructions). I can add images to the e-mail template and they display OK in the interface.

When sending test e-mails, system says unexpected errors, please contact us.

Below is my GIT bash log. Could you help me decipher it?

```
Duc@ibm-x230-n003 MINGW64 ~/Documents/GitHub/mosaico (master)
$ grunt
Running "bowercopy:libs" (bowercopy) task
C:\Users\Duc\Documents\GitHub\mosaico\bower_components\knockout\dist\knockout.js -> dist\vendor\knockout.js
C:\Users\Duc\Documents\GitHub\mosaico\bower_components\jquery\dist\jquery.min.js -> dist\vendor\jquery.min.js
C:\Users\Duc\Documents\GitHub\mosaico\bower_components\jquery\dist\jquery.min.map -> dist\vendor\jquery.min.map
C:\Users\Duc\Documents\GitHub\mosaico\bower_components\jquery-ui\jquery-ui.min.js -> dist\vendor\jquery-ui.min.js
C:\Users\Duc\Documents\GitHub\mosaico\bower_components\jquery-ui\themes\smoothness\jquery-ui.min.css -> dist\vendor\jquery-ui.min.css
C:\Users\Duc\Documents\GitHub\mosaico\bower_components\jqueryui-touch-punch\jquery.ui.touch-punch.min.js -> dist\vendor\jquery.ui.touch-punch.min.js
C:\Users\Duc\Documents\GitHub\mosaico\bower_components\knockout-jqueryui\dist\knockout-jqueryui.min.js -> dist\vendor\knockout-jqueryui.min.js
C:\Users\Duc\Documents\GitHub\mosaico\bower_components\blueimp-canvas-to-blob\js\canvas-to-blob.min.js -> dist\vendor\canvas-to-blob.min.js
C:\Users\Duc\Documents\GitHub\mosaico\bower_components\blueimp-load-image\js\load-image.all.min.js -> dist\vendor\load-image.all.min.js
C:\Users\Duc\Documents\GitHub\mosaico\bower_components\jquery-file-upload\js\jquery.iframe-transport.js -> dist\vendor\jquery.iframe-transport.js
C:\Users\Duc\Documents\GitHub\mosaico\bower_components\jquery-file-upload\js\jquery.fileupload.js -> dist\vendor\jquery.fileupload.js
C:\Users\Duc\Documents\GitHub\mosaico\bower_components\jquery-file-upload\js\jquery.fileupload-process.js -> dist\vendor\jquery.fileupload-process.js
C:\Users\Duc\Documents\GitHub\mosaico\bower_components\jquery-file-upload\js\jquery.fileupload-image.js -> dist\vendor\jquery.fileupload-image.js
C:\Users\Duc\Documents\GitHub\mosaico\bower_components\jquery-file-upload\js\jquery.fileupload-validate.js -> dist\vendor\jquery.fileupload-validate.js
C:\Users\Duc\Documents\GitHub\mosaico\bower_components\tinymce\tinymce.min.js -> dist\vendor\tinymce.min.js
C:\Users\Duc\Documents\GitHub\mosaico\bower_components\tinymce\themes -> dist\vendor\themes
C:\Users\Duc\Documents\GitHub\mosaico\bower_components\tinymce\skins -> dist\vendor\skins
C:\Users\Duc\Documents\GitHub\mosaico\bower_components\tinymce\plugins -> dist\vendor\plugins
C:\Users\Duc\Documents\GitHub\mosaico\bower_components\webfont-notosans\regular -> dist\vendor\notoregular

Running "bowercopy:fontawesome" (bowercopy) task
C:\Users\Duc\Documents\GitHub\mosaico\bower_components\font-awesome\fonts\fontawesome-webfont.woff2 -> dist\fa\fonts\fontawesome-webfont.woff2
C:\Users\Duc\Documents\GitHub\mosaico\bower_components\font-awesome\fonts\fontawesome-webfont.woff -> dist\fa\fonts\fontawesome-webfont.woff
C:\Users\Duc\Documents\GitHub\mosaico\bower_components\font-awesome\fonts\fontawesome-webfont.ttf -> dist\fa\fonts\fontawesome-webfont.ttf
C:\Users\Duc\Documents\GitHub\mosaico\bower_components\font-awesome\fonts\fontawesome-webfont.svg -> dist\fa\fonts\fontawesome-webfont.svg
C:\Users\Duc\Documents\GitHub\mosaico\bower_components\font-awesome\fonts\fontawesome-webfont.eot -> dist\fa\fonts\fontawesome-webfont.eot
Some bower components are not configured:  [ 'knockout-sortable',
  'knockoutjs-reactor',
  'mensch',
  'toastr',
  'knockout-undomanager',
  'knockout.wrap',
  'jquery.iframe-transport',
  'console-browserify',
  'blueimp-file-upload',
  'evol-colorpicker',
  'jsep',
  'juice',
  'slick',
  'tinycolor' ]

Running "copy:res" (copy) task
Created 7 directories, copied 36 files

Running "jshint:all" (jshint) task

√ No problems


Running "combineKOTemplates:main" (combineKOTemplates) task

Running "browserify:debug" (browserify) task
>> Bundle build/mosaico.js created.

Running "browserify:main" (browserify) task
>> Bundle build/mosaico.debug.js created.

Running "exorcise:main" (exorcise) task
Exorcising source map from build/mosaico.debug.js

Running "less:css" (less) task
>> 2 stylesheets created.

Running "postcss:dist" (postcss) task
>> 1 processed stylesheet created.
>> 1 sourcemap created.

Running "postcss:material" (postcss) task
>> 1 processed stylesheet created.
>> 1 sourcemap created.

Running "express:dev" (express) task
Starting background Express server
Express server listening on port 9006

Running "watch" task
Waiting...
TypeError: Cannot read property 'split' of undefined
    at C:\Users\Duc\Documents\GitHub\mosaico\backend\main.js:76:34
    at Layer.handle [as handle_request] (C:\Users\Duc\Documents\GitHub\mosaico\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Duc\Documents\GitHub\mosaico\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (C:\Users\Duc\Documents\GitHub\mosaico\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Duc\Documents\GitHub\mosaico\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Duc\Documents\GitHub\mosaico\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (C:\Users\Duc\Documents\GitHub\mosaico\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\Duc\Documents\GitHub\mosaico\node_modules\express\lib\router\index.js:271:10)
    at urlencodedParser (C:\Users\Duc\Documents\GitHub\mosaico\node_modules\body-parser\lib\types\urlencoded.js:91:7)
    at Layer.handle [as handle_request] (C:\Users\Duc\Documents\GitHub\mosaico\node_modules\express\lib\router\layer.js:95:5)
TypeError: Cannot read property 'split' of undefined
    at C:\Users\Duc\Documents\GitHub\mosaico\backend\main.js:76:34
    at Layer.handle [as handle_request] (C:\Users\Duc\Documents\GitHub\mosaico\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Duc\Documents\GitHub\mosaico\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (C:\Users\Duc\Documents\GitHub\mosaico\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Duc\Documents\GitHub\mosaico\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Duc\Documents\GitHub\mosaico\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (C:\Users\Duc\Documents\GitHub\mosaico\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\Duc\Documents\GitHub\mosaico\node_modules\express\lib\router\index.js:271:10)
    at urlencodedParser (C:\Users\Duc\Documents\GitHub\mosaico\node_modules\body-parser\lib\types\urlencoded.js:91:7)
    at Layer.handle [as handle_request] (C:\Users\Duc\Documents\GitHub\mosaico\node_modules\express\lib\router\layer.js:95:5)
TypeError: Cannot read property 'split' of undefined
    at C:\Users\Duc\Documents\GitHub\mosaico\backend\main.js:76:34
    at Layer.handle [as handle_request] (C:\Users\Duc\Documents\GitHub\mosaico\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Duc\Documents\GitHub\mosaico\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (C:\Users\Duc\Documents\GitHub\mosaico\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Duc\Documents\GitHub\mosaico\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Duc\Documents\GitHub\mosaico\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (C:\Users\Duc\Documents\GitHub\mosaico\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\Duc\Documents\GitHub\mosaico\node_modules\express\lib\router\index.js:271:10)
    at urlencodedParser (C:\Users\Duc\Documents\GitHub\mosaico\node_modules\body-parser\lib\types\urlencoded.js:91:7)
    at Layer.handle [as handle_request] (C:\Users\Duc\Documents\GitHub\mosaico\node_modules\express\lib\router\layer.js:95:5)
{ Error: connect ECONNREFUSED 127.0.0.1:25
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
  code: 'ECONNECTION',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 25,
  command: 'CONN' }
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:441:15)
    at C:\Users\Duc\Documents\GitHub\mosaico\backend\main.js:138:25
    at Nodemailer.<anonymous> (C:\Users\Duc\Documents\GitHub\mosaico\node_modules\nodemailer\lib\nodemailer.js:329:26)
    at SMTPConnection.<anonymous> (C:\Users\Duc\Documents\GitHub\mosaico\node_modules\nodemailer-smtp-transport\lib\smtp-transport.js:105:20)
    at SMTPConnection.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at SMTPConnection.emit (events.js:188:7)
    at SMTPConnection._onError (C:\Users\Duc\Documents\GitHub\mosaico\node_modules\smtp-connection\lib\smtp-connection.js:518:10)
    at SMTPConnection.<anonymous> (C:\Users\Duc\Documents\GitHub\mosaico\node_modules\smtp-connection\lib\smtp-connection.js:240:14)
    at emitOne (events.js:96:13)
Stopping Express server](url)
```

**Comment by bago** [comment]
server-config.js must be configured according to the email sending service you want to use.
By default it tries localhost smtp server and it seems you don't have an smtp server on localhost.
