### ISSUE TITLE
During Image Upload express-server stops automatically

### ISSUE THREAD

**Issue by vikrantsiwach** [voidlabs/mosaico#345]
I successfully integrate mosaico.io into our local(localhost:9006). I am on Mac OS X EI Capiton 10.11.3
I also installed Image magick (sudo port install ImageMagick).And on type "convert" it shows me help option.
But I can't Upload the image due to some reason and images are broken
GET : 200 response on this URL http://localhost:9006/img/?method=placeholder&params=166%2C130 , but no image was there
And on upload http://localhost:9006/upload/ , it just shows provisional headers are shown in the network tab and express-server automatically stops with the error
 
[ '166', '130' ] 'params are here'
gm {
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  _options: { imageMagick: true },
  data: {},
  _in: [],
  _out: [],
  _outputFormat: null,
  _subCommand: 'convert',
  source: '',
  _sourceFormatters: [ [Function] ],
  outname: 'png:-' } 'out is here'
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn convert ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
Stopping Express server

Hope you can reply and help me out.
Thanks
Vikrant siwach

**Comment by vikrantsiwach** [comment]
It's fixed for me. I have to close the terminal tab and open it again to make it work. what a waste of time. :)
But not working for apache, any suggestion. I have all things installed. It means i think for apache imagemagick not working.

**Comment by bago** [comment]
I don't know what you mean "for apache" as the demo is just node.js. Mosaico is a browser library.. so the backend issues do not belong to this project unless you think the mosaico library is doing bad calls.

**Comment by bago** [comment]
I mean: Apache is a webserver, not a backend. So Apache alone will not do anything to mosaico. If you have a specific issue with a specific backend served VIA apache then you'll probably have more details (and maybe a different project to report against).
