### ISSUE TITLE
Images don't show up on editor 

### ISSUE THREAD

**Issue by sorin21** [voidlabs/mosaico#396]
I tried to install mosaico like a standalone application and then to make a connection from mosaico folder to any app that I want. The problem is that, after I select a theme and add a block, when I click on add image, the image shows up for 1 second then disappears.

In both cases: with nodejs or php backend I get the same issues. 
-looks like you have to copy and paste in the browser the links from screenshots so see them
This screenshot is when I use nodejs [http://prntscr.com/hvybtj](url)
In this case I don't get any error, the image shows up 1 second and disappers, but in the uploads folder the image shows up.

In the php case the screenshot is [https://prnt.sc/hvy6nt](url)
Here I can see some errors but I couldn't figure out how to solve them. I preferred to see the errors in js case because I know better js then PHP. In this case same problem, the image shows up for 1 sec and disappears, but in the uploads folder there is not image in the end(different then the js case).

I checked, for both cases the folders rights and I can read and write on both. Everything is on localhost.

Can someone please help me to figure out what is going on?

**Comment by bago** [comment]
Please read this and add missing informations:
https://github.com/voidlabs/mosaico/blob/master/CONTRIBUTING.md

**Comment by bago** [comment]
Hi, i'm sorry I don't have time to debug old releases (it seems you're trying to use mosaico 0.15, don't know why). 

Check out current master here: https://github.com/voidlabs/mosaico/archive/master.zip
And run grunt.

**Comment by sorin21** [comment]
Thank you for your link, but still I get the same problem with images. When I try to upload show up and very fast disappear from editor. I can find them in the upload folder, but  if I send an email I get the email just with text, no images. 

I downloaded your zip and then ran npm install. The output:

```
D:\projects\mosaico\node_modules\mosaico (master -> origin) (mosaico@0.16.0)
λ npm install
npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm WARN deprecated bower@1.3.12: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm WARN deprecated coffee-script@1.10.0: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated http2@3.3.7: Use the built-in module in node 9.0.0 or newer, instead
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@0.12.1: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm

> mosaico@0.16.0 postinstall D:\projects\mosaico\node_modules\mosaico
> bower -V --allow-root install

bower knockout.wrap#mosaico not-cached https://github.com/bago/knockout.wrap.git#mosaico
bower knockout.wrap#mosaico    resolve https://github.com/bago/knockout.wrap.git#mosaico
bower evol-colorpicker#mosaico       not-cached https://github.com/bago/colorpicker.git#mosaico
bower evol-colorpicker#mosaico          resolve https://github.com/bago/colorpicker.git#mosaico
bower knockoutjs-reactor#~1.4.0-beta not-cached https://github.com/ZiadJ/knockoutjs-reactor.git#~1.4.0-beta
bower knockoutjs-reactor#~1.4.0-beta    resolve https://github.com/ZiadJ/knockoutjs-reactor.git#~1.4.0-beta
bower jqueryui-touch-punch#*         not-cached https://github.com/furf/jquery-ui-touch-punch.git#*
bower jqueryui-touch-punch#*            resolve https://github.com/furf/jquery-ui-touch-punch.git#*
bower jquery-file-upload#~9.19.1     not-cached https://github.com/blueimp/jQuery-File-Upload.git#~9.19.1
bower jquery-file-upload#~9.19.1        resolve https://github.com/blueimp/jQuery-File-Upload.git#~9.19.1
bower blueimp-load-image#~2.17.0     not-cached https://github.com/blueimp/JavaScript-Load-Image.git#~2.17.0
bower blueimp-load-image#~2.17.0        resolve https://github.com/blueimp/JavaScript-Load-Image.git#~2.17.0
bower jquery-ui#~1.11.4              not-cached https://github.com/components/jqueryui.git#~1.11.4
bower jquery-ui#~1.11.4                 resolve https://github.com/components/jqueryui.git#~1.11.4
bower blueimp-file-upload#~9.19.1    not-cached https://github.com/blueimp/jQuery-File-Upload.git#~9.19.1
bower blueimp-file-upload#~9.19.1       resolve https://github.com/blueimp/jQuery-File-Upload.git#~9.19.1
bower font-awesome#~4.7.0            not-cached https://github.com/FortAwesome/Font-Awesome.git#~4.7.0
bower font-awesome#~4.7.0               resolve https://github.com/FortAwesome/Font-Awesome.git#~4.7.0
bower tinymce#~4.7.2                 not-cached https://github.com/tinymce/tinymce-dist.git#~4.7.2
bower tinymce#~4.7.2                    resolve https://github.com/tinymce/tinymce-dist.git#~4.7.2
bower knockout-jqueryui#~2.2.3           cached https://github.com/gvas/knockout-jqueryui.git#2.2.3
bower knockout-jqueryui#~2.2.3         validate 2.2.3 against https://github.com/gvas/knockout-jqueryui.git#~2.2.3
bower juice#~3.0.1                       cached https://github.com/Automattic/juice.git#3.0.1
bower juice#~3.0.1                     validate 3.0.1 against https://github.com/Automattic/juice.git#~3.0.1
bower slick#~1.12.2                      cached https://github.com/kamicane/slick.git#1.12.2
bower slick#~1.12.2                    validate 1.12.2 against https://github.com/kamicane/slick.git#~1.12.2
bower blueimp-canvas-to-blob#~3.14.0     cached https://github.com/blueimp/JavaScript-Canvas-to-Blob.git#3.14.0
bower blueimp-canvas-to-blob#~3.14.0   validate 3.14.0 against https://github.com/blueimp/JavaScript-Canvas-to-Blob.git#~3.14.0
bower toastr#~2.1.0                      cached https://github.com/johnpapa/toastr-bower.git#2.1.3
bower toastr#~2.1.0                    validate 2.1.3 against https://github.com/johnpapa/toastr-bower.git#~2.1.0
bower knockout-undomanager#~0.2.1        cached https://github.com/bago/knockout-undomanager.git#0.2.1
bower knockout-undomanager#~0.2.1      validate 0.2.1 against https://github.com/bago/knockout-undomanager.git#~0.2.1
bower console-browserify#~1.0.3          cached https://github.com/Raynos/console-browserify.git#1.0.3
bower console-browserify#~1.0.3        validate 1.0.3 against https://github.com/Raynos/console-browserify.git#~1.0.3
bower tinycolor#~1.4.1                   cached https://github.com/bgrins/TinyColor.git#1.4.1
bower tinycolor#~1.4.1                 validate 1.4.1 against https://github.com/bgrins/TinyColor.git#~1.4.1
bower jquery#~1.12.4                     cached https://github.com/jquery/jquery-dist.git#1.12.4
bower jquery#~1.12.4                   validate 1.12.4 against https://github.com/jquery/jquery-dist.git#~1.12.4
bower jsep#~0.3.1                        cached https://github.com/soney/jsep.git#0.3.3
bower jsep#~0.3.1                      validate 0.3.3 against https://github.com/soney/jsep.git#~0.3.1
bower webfont-notosans#~0.1.0            cached https://github.com/jjlharrison/webfont-notosans.git#0.1.0
bower webfont-notosans#~0.1.0          validate 0.1.0 against https://github.com/jjlharrison/webfont-notosans.git#~0.1.0
bower knockout-sortable#~0.15.0          cached https://github.com/rniemeyer/knockout-sortable.git#0.15.0
bower knockout-sortable#~0.15.0        validate 0.15.0 against https://github.com/rniemeyer/knockout-sortable.git#~0.15.0
bower jquery.iframe-transport#~1.0.0     cached https://github.com/cmlenz/jquery-iframe-transport.git#1.0.1
bower jquery.iframe-transport#~1.0.0   validate 1.0.1 against https://github.com/cmlenz/jquery-iframe-transport.git#~1.0.0
bower mensch#~0.3.3                      cached https://github.com/brettstimmerman/mensch.git#0.3.3
bower mensch#~0.3.3                    validate 0.3.3 against https://github.com/brettstimmerman/mensch.git#~0.3.3
bower knockout#3.4.0 - 3.4.2             cached https://github.com/SteveSanderson/knockout.git#3.4.2
bower knockout#3.4.0 - 3.4.2           validate 3.4.2 against https://github.com/SteveSanderson/knockout.git#3.4.0 - 3.4.2
bower knockoutjs-reactor#~1.4.0-beta   download https://github.com/ZiadJ/knockoutjs-reactor/archive/v1.4.0-beta.tar.gz
bower knockout.wrap#mosaico            download https://github.com/bago/knockout.wrap/archive/mosaico.tar.gz
bower knockout#>=2.2                     cached https://github.com/SteveSanderson/knockout.git#3.4.2
bower knockout#>=2.2                   validate 3.4.2 against https://github.com/SteveSanderson/knockout.git#>=2.2
bower jquery-ui#>=1.8                    cached https://github.com/components/jqueryui.git#1.12.1
bower jquery-ui#>=1.8                  validate 1.12.1 against https://github.com/components/jqueryui.git#>=1.8
bower jqueryui-touch-punch#*           download https://github.com/furf/jquery-ui-touch-punch/archive/master.tar.gz
bower evol-colorpicker#mosaico         download https://github.com/bago/colorpicker/archive/mosaico.tar.gz
bower jquery-ui#~1.11.4                download https://github.com/components/jqueryui/archive/1.11.4.tar.gz
bower jquery#>=1.6                       cached https://github.com/jquery/jquery-dist.git#3.2.1
bower jquery#>=1.6                     validate 3.2.1 against https://github.com/jquery/jquery-dist.git#>=1.6
bower knockoutjs-reactor#~1.4.0-beta    extract archive.tar.gz
bower knockoutjs-reactor#~1.4.0-beta     invalid-meta for:C:\Users\SORINE~1.DRA\AppData\Local\Temp\HUB-sorinel.dragomir\bower\461cc94abdf68d041312e5bf93c86276-4540-yGUSid\bower.json
bower knockoutjs-reactor#~1.4.0-beta     invalid-meta The "main" field cannot contain minified files
bower blueimp-load-image#~2.17.0             download https://github.com/blueimp/JavaScript-Load-Image/archive/v2.17.1.tar.gz
bower blueimp-file-upload#~9.19.1            download https://github.com/blueimp/jQuery-File-Upload/archive/v9.19.2.tar.gz
bower jquery-file-upload#~9.19.1             download https://github.com/blueimp/jQuery-File-Upload/archive/v9.19.2.tar.gz
bower knockout.wrap#mosaico                   extract archive.tar.gz
bower knockoutjs-reactor#~1.4.0-beta         resolved https://github.com/ZiadJ/knockoutjs-reactor.git#1.4.0-beta
bower knockout.wrap#mosaico                  resolved https://github.com/bago/knockout.wrap.git#6d45d1e282
bower jqueryui-touch-punch#*                  extract archive.tar.gz
bower jqueryui-touch-punch#*             invalid-meta for:C:\Users\SORINE~1.DRA\AppData\Local\Temp\HUB-sorinel.dragomir\bower\8b5ae802b5d5d60a7852347dd80290eb-4540-4QGb77\bower.json
bower jqueryui-touch-punch#*             invalid-meta The "main" field cannot contain minified files
bower jqueryui-touch-punch#*                 resolved https://github.com/furf/jquery-ui-touch-punch.git#4bc0091452
bower jquery#>=1.6.3 <3                        cached https://github.com/jquery/jquery-dist.git#2.2.4
bower jquery#>=1.6.3 <3                      validate 2.2.4 against https://github.com/jquery/jquery-dist.git#>=1.6.3 <3
bower font-awesome#~4.7.0                    download https://github.com/FortAwesome/Font-Awesome/archive/v4.7.0.tar.gz
bower knockout#>=3.0.0                         cached https://github.com/SteveSanderson/knockout.git#3.4.2
bower knockout#>=3.0.0                       validate 3.4.2 against https://github.com/SteveSanderson/knockout.git#>=3.0.0
bower evol-colorpicker#mosaico                extract archive.tar.gz
bower evol-colorpicker#mosaico           invalid-meta for:C:\Users\SORINE~1.DRA\AppData\Local\Temp\HUB-sorinel.dragomir\bower\76b92d8e23af58299307ac8631421fa3-4540-F3dTuq\bower.json
bower evol-colorpicker#mosaico           invalid-meta The "main" field cannot contain minified files
bower evol-colorpicker#mosaico           invalid-meta The "main" field cannot contain minified files
bower evol-colorpicker#mosaico               resolved https://github.com/bago/colorpicker.git#8614d91c6f
bower blueimp-file-upload#~9.19.1             extract archive.tar.gz
bower jquery-file-upload#~9.19.1              extract archive.tar.gz
bower blueimp-load-image#~2.17.0              extract archive.tar.gz
bower jquery-ui#~1.11.4                       extract archive.tar.gz
bower blueimp-file-upload#~9.19.1            resolved https://github.com/blueimp/jQuery-File-Upload.git#9.19.2
bower blueimp-load-image#>=1.13.0              cached https://github.com/blueimp/JavaScript-Load-Image.git#2.6.2
bower blueimp-load-image#>=1.13.0            validate 2.6.2 against https://github.com/blueimp/JavaScript-Load-Image.git#>=1.13.0
bower blueimp-load-image#>=1.13.0                 new version for https://github.com/blueimp/JavaScript-Load-Image.git#>=1.13.0
bower blueimp-load-image#>=1.13.0             resolve https://github.com/blueimp/JavaScript-Load-Image.git#>=1.13.0
bower blueimp-load-image#>=1.13.0            download https://github.com/blueimp/JavaScript-Load-Image/archive/v2.17.1.tar.gz
bower blueimp-tmpl#>=2.5.4                     cached https://github.com/blueimp/JavaScript-Templates.git#3.11.0
bower blueimp-tmpl#>=2.5.4                   validate 3.11.0 against https://github.com/blueimp/JavaScript-Templates.git#>=2.5.4
bower blueimp-load-image#~2.17.0             resolved https://github.com/blueimp/JavaScript-Load-Image.git#2.17.1
bower tinymce#~4.7.2                         download https://github.com/tinymce/tinymce-dist/archive/4.7.4.tar.gz
bower jquery-file-upload#~9.19.1             resolved https://github.com/blueimp/jQuery-File-Upload.git#9.19.2
bower blueimp-load-image#>=1.13.0             extract archive.tar.gz
bower blueimp-load-image#>=1.13.0            resolved https://github.com/blueimp/JavaScript-Load-Image.git#2.17.1
bower jquery-ui#~1.11.4                      resolved https://github.com/components/jqueryui.git#1.11.4
bower font-awesome#~4.7.0                     extract archive.tar.gz
bower tinymce#~4.7.2                          extract archive.tar.gz
bower tinymce#~4.7.2                         resolved https://github.com/tinymce/tinymce-dist.git#4.7.4
bower font-awesome#~4.7.0                    resolved https://github.com/FortAwesome/Font-Awesome.git#4.7.0
bower knockout                       extra-resolution Unnecessary resolution: knockout#3.4.1
bower knockout-jqueryui#~2.2.3                install knockout-jqueryui#2.2.3
bower juice#~3.0.1                            install juice#3.0.1
bower slick#~1.12.2                           install slick#1.12.2
bower jquery-ui#~1.11.4                       install jquery-ui#1.11.4
bower knockoutjs-reactor#~1.4.0-beta          install knockoutjs-reactor#1.4.0-beta
bower knockout.wrap#mosaico                   install knockout.wrap#6d45d1e282
bower toastr#~2.1.0                           install toastr#2.1.3
bower jqueryui-touch-punch#*                  install jqueryui-touch-punch#4bc0091452
bower blueimp-canvas-to-blob#~3.14.0          install blueimp-canvas-to-blob#3.14.0
bower knockout-undomanager#~0.2.1             install knockout-undomanager#0.2.1
bower evol-colorpicker#mosaico                install evol-colorpicker#8614d91c6f
bower console-browserify#~1.0.3               install console-browserify#1.0.3
bower tinycolor#~1.4.1                        install tinycolor#1.4.1
bower jquery#~1.12.4                          install jquery#1.12.4
bower webfont-notosans#~0.1.0                 install webfont-notosans#0.1.0
bower jsep#~0.3.1                             install jsep#0.3.3
bower knockout-sortable#~0.15.0               install knockout-sortable#0.15.0
bower blueimp-file-upload#~9.19.1             install blueimp-file-upload#9.19.2
bower jquery.iframe-transport#~1.0.0          install jquery.iframe-transport#1.0.1
bower blueimp-load-image#~2.17.0              install blueimp-load-image#2.17.1
bower mensch#~0.3.3                           install mensch#0.3.3
bower jquery-file-upload#~9.19.1              install jquery-file-upload#9.19.2
bower knockout#>=2.2                          install knockout#3.4.2
bower blueimp-tmpl#>=2.5.4                    install blueimp-tmpl#3.11.0
bower tinymce#~4.7.2                          install tinymce#4.7.4
bower font-awesome#~4.7.0                     install font-awesome#4.7.0

knockout-jqueryui#2.2.3 bower_components\knockout-jqueryui
├── jquery-ui#1.11.4
└── knockout#3.4.2

juice#3.0.1 bower_components\juice

slick#1.12.2 bower_components\slick

jquery-ui#1.11.4 bower_components\jquery-ui
└── jquery#1.12.4

knockoutjs-reactor#1.4.0-beta bower_components\knockoutjs-reactor
└── knockout#3.4.2

knockout.wrap#6d45d1e282 bower_components\knockout.wrap

toastr#2.1.3 bower_components\toastr
└── jquery#1.12.4

jqueryui-touch-punch#4bc0091452 bower_components\jqueryui-touch-punch
├── jquery#1.12.4
└── jquery-ui#1.11.4

blueimp-canvas-to-blob#3.14.0 bower_components\blueimp-canvas-to-blob

knockout-undomanager#0.2.1 bower_components\knockout-undomanager
└── knockout#3.4.2

evol-colorpicker#8614d91c6f bower_components\evol-colorpicker

console-browserify#1.0.3 bower_components\console-browserify

tinycolor#1.4.1 bower_components\tinycolor

jquery#1.12.4 bower_components\jquery

webfont-notosans#0.1.0 bower_components\webfont-notosans

jsep#0.3.3 bower_components\jsep

knockout-sortable#0.15.0 bower_components\knockout-sortable

blueimp-file-upload#9.19.2 bower_components\blueimp-file-upload
├── blueimp-canvas-to-blob#3.14.0
├── blueimp-load-image#2.17.1
├── blueimp-tmpl#3.11.0
└── jquery#1.12.4

jquery.iframe-transport#1.0.1 bower_components\jquery.iframe-transport
└── jquery#1.12.4

blueimp-load-image#2.17.1 bower_components\blueimp-load-image

mensch#0.3.3 bower_components\mensch

jquery-file-upload#9.19.2 bower_components\jquery-file-upload
├── blueimp-canvas-to-blob#3.14.0
├── blueimp-load-image#2.17.1
├── blueimp-tmpl#3.11.0
└── jquery#1.12.4

knockout#3.4.2 bower_components\knockout

blueimp-tmpl#3.11.0 bower_components\blueimp-tmpl

tinymce#4.7.4 bower_components\tinymce

font-awesome#4.7.0 bower_components\font-awesome
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 956 packages in 88.192s
```


Then ran the command grunt. 

The output was:

```
D:\projects\mosaico\node_modules\mosaico (master -> origin) (mosaico@0.16.0)
λ grunt
(node:932) ExperimentalWarning: The http2 module is an experimental API.
Running "bowercopy:libs" (bowercopy) task
D:\projects\mosaico\node_modules\mosaico\bower_components\knockout\dist\knockout.js -> dist\vendor\knockout.js
D:\projects\mosaico\node_modules\mosaico\bower_components\jquery\dist\jquery.min.js -> dist\vendor\jquery.min.js
D:\projects\mosaico\node_modules\mosaico\bower_components\jquery\dist\jquery.min.map -> dist\vendor\jquery.min.map
D:\projects\mosaico\node_modules\mosaico\bower_components\jquery-ui\jquery-ui.min.js -> dist\vendor\jquery-ui.min.js
D:\projects\mosaico\node_modules\mosaico\bower_components\jquery-ui\themes\smoothness\jquery-ui.min.css -> dist\vendor\jquery-ui.min.css
D:\projects\mosaico\node_modules\mosaico\bower_components\jqueryui-touch-punch\jquery.ui.touch-punch.min.js -> dist\vendor\jquery.ui.touch-punch.min.js
D:\projects\mosaico\node_modules\mosaico\bower_components\knockout-jqueryui\dist\knockout-jqueryui.min.js -> dist\vendor\knockout-jqueryui.min.js
D:\projects\mosaico\node_modules\mosaico\bower_components\blueimp-canvas-to-blob\js\canvas-to-blob.min.js -> dist\vendor\canvas-to-blob.min.js
D:\projects\mosaico\node_modules\mosaico\bower_components\blueimp-load-image\js\load-image.all.min.js -> dist\vendor\load-image.all.min.js
D:\projects\mosaico\node_modules\mosaico\bower_components\jquery-file-upload\js\jquery.iframe-transport.js -> dist\vendor\jquery.iframe-transport.js
D:\projects\mosaico\node_modules\mosaico\bower_components\jquery-file-upload\js\jquery.fileupload.js -> dist\vendor\jquery.fileupload.js
D:\projects\mosaico\node_modules\mosaico\bower_components\jquery-file-upload\js\jquery.fileupload-process.js -> dist\vendor\jquery.fileupload-process.js
D:\projects\mosaico\node_modules\mosaico\bower_components\jquery-file-upload\js\jquery.fileupload-image.js -> dist\vendor\jquery.fileupload-image.js
D:\projects\mosaico\node_modules\mosaico\bower_components\jquery-file-upload\js\jquery.fileupload-validate.js -> dist\vendor\jquery.fileupload-validate.js
D:\projects\mosaico\node_modules\mosaico\bower_components\tinymce\tinymce.min.js -> dist\vendor\tinymce.min.js
D:\projects\mosaico\node_modules\mosaico\bower_components\tinymce\themes -> dist\vendor\themes
D:\projects\mosaico\node_modules\mosaico\bower_components\tinymce\skins -> dist\vendor\skins
D:\projects\mosaico\node_modules\mosaico\bower_components\tinymce\plugins -> dist\vendor\plugins
D:\projects\mosaico\node_modules\mosaico\bower_components\webfont-notosans\regular -> dist\vendor\notoregular

Running "bowercopy:fontawesome" (bowercopy) task
D:\projects\mosaico\node_modules\mosaico\bower_components\font-awesome\fonts\fontawesome-webfont.woff2 -> dist\fa\fonts\fontawesome-webfont.woff2
D:\projects\mosaico\node_modules\mosaico\bower_components\font-awesome\fonts\fontawesome-webfont.woff -> dist\fa\fonts\fontawesome-webfont.woff
D:\projects\mosaico\node_modules\mosaico\bower_components\font-awesome\fonts\fontawesome-webfont.ttf -> dist\fa\fonts\fontawesome-webfont.ttf
D:\projects\mosaico\node_modules\mosaico\bower_components\font-awesome\fonts\fontawesome-webfont.svg -> dist\fa\fonts\fontawesome-webfont.svg
D:\projects\mosaico\node_modules\mosaico\bower_components\font-awesome\fonts\fontawesome-webfont.eot -> dist\fa\fonts\fontawesome-webfont.eot
Some bower components are not configured:  [ 'knockout-sortable',
  'knockoutjs-reactor',
  'mensch',
  'toastr',
  'knockout-undomanager',
  'knockout.wrap',
  'jquery.iframe-transport',
  'console-browserify',
  'blueimp-file-upload',
  'evol-colorpicker',
  'jsep',
  'juice',
  'slick',
  'tinycolor' ]

Running "copy:res" (copy) task
Created 7 directories, copied 39 files

Running "jshint:all" (jshint) task

√ No problems


Running "combineKOTemplates:main" (combineKOTemplates) task

Running "browserify:debug" (browserify) task
(node:932) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
>> 504896 bytes written (0.69 seconds)
>> Bundle build/mosaico.js created.

Running "browserify:main" (browserify) task
>> 1159309 bytes written (1.17 seconds)
>> Bundle build/mosaico.debug.js created.

Running "exorcise:main" (exorcise) task
Exorcising source map from build/mosaico.debug.js

Running "less:css" (less) task
>> 2 stylesheets created.

Running "postcss:dist" (postcss) task
>> 1 processed stylesheet created.
>> 1 sourcemap created.

Running "postcss:material" (postcss) task
>> 1 processed stylesheet created.
>> 1 sourcemap created.

Running "express:dev" (express) task
Starting background Express server
Express server listening on port 9006

Running "watch" task
Waiting...
ImageMagick failed to run self-check image format detection. Error: Error: Could not execute GraphicsMagick/ImageMagick: identify "-ping" "-format" "%m" "" this most likely means the gm/convert binaries can't be found
    at ChildProcess.<anonymous> (D:\projects\mosaico\node_modules\mosaico\node_modules\gm\lib\command.js:232:12)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at ChildProcess.cp.emit (D:\projects\mosaico\node_modules\mosaico\node_modules\cross-spawn\lib\enoent.js:36:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

```

**Comment by sorin21** [comment]
Bago, someone told me that I didn't installed correctly ImageMagick  or I didn't install it at all. He was right. Because I'm on windows I didn't add it to the environment variables path. So after I did this worked perfectly.

**Comment by bago** [comment]
Well, it is written in the README:
https://github.com/voidlabs/mosaico/blob/master/README.md

> IMPORTANT in order to use image uploading/processing feature in Node you need imageMagick installed in your environment. e.g. **running "convert" and "identify" on the command line should output imageMagick command line help** (if you are on Windows and install imageMagick 7.x then make sure to install "legacy utilities").
