### ISSUE TITLE
Images dont work

### ISSUE THREAD

**Issue by Rasker13** [voidlabs/mosaico#613]
Hello!
Sorry for my english.
I spend 2 weeks for integrate mosaico, but pictures don't work. Preloaded and downloaded https://prnt.sc/1w8xch9
It show for 2 seconds and disappear with error ""
I use windows 10.
I'll tell about my process:
1. Create project
2. download node in project "npm i node@lts"
3. download latest .exe ImageMagick from https://imagemagick.org/script/download.php#windows
4. install ImageMagick with "legacy utilities" https://prnt.sc/1w8ydbo in project directory
5. download and unzip mosaico to project
6. in console "npm install"
7. "npm audit fix" - after fixes:  28 vulnerabilities (8 moderate, 19 high, 1 critical)
8. "npm install -g grunt-cli"
9. "grunt" - http://127.0.0.1:9006

Where is i make mistake?

Any template 

Grunt
`D:\vrem\moz\mosaico-master-link>grunt
(node:13108) [DEP0128] DeprecationWarning: Invalid 'main' field in 'D:\vrem\moz\mosaico-master-link\node_modules\mold-source-map\package.json' of 'mold-source-map.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:13108) Warning: Accessing non-existent property 'VERSION' of module exports inside circular dependency
Running "googlefonts:noto" (googlefonts) task
>> 1 font downloaded.

6 directories, copied 41 files

Running "copy:root" (copy) task
Copied 1 file

Running "copy:htmls" (copy) task
Copied 2 files

Running "copy:fontawesome" (copy) task
Copied 5 files

Running "uglify:deps" (uglify) task
>> 1 sourcemap created.
>> 1 file created 2.44 MB → 947.88 kB

Running "cssmin:deps" (cssmin) task
>> 1 file created. 358 B → 322 B

Running "jshint:all" (jshint) task

√ No problems

Running "combineKOTemplates:main" (combineKOTemplates) task

Running "browserify:main" (browserify) task
(node:13108) [DEP0128] DeprecationWarning: Invalid 'main' field in 'D:\vrem\moz\mosaico-master-link\node_modules\find-parent-dir\package.json' of 'find-parent-dir.js'. Please either fix that or report it to the module author
>> 1376986 bytes written (0.32 seconds)
>> Bundle build/mosaico.inlinesourcemap.js created.

Running "exorcise:main" (exorcise) task
Exorcising source map from build/mosaico.inlinesourcemap.js

Running "uglify:min" (uglify) task
>> 1 sourcemap created.
>> 1 file created 541.64 kB → 231.05 kB

Running "less:css" (less) task
>> 2 stylesheets created.

Running "postcss:dist" (postcss) task
>> 1 processed stylesheet created.
>> 1 sourcemap created.

Running "postcss:material" (postcss) task
>> 1 processed stylesheet created.
>> 1 sourcemap created.

Running "express:dev" (express) task
Starting background Express server
Express server listening on port 9006

Running "watch" task
Waiting...
TypeError: os.tmpDir is not a function
    at new IncomingForm (D:\vrem\moz\mosaico-master-link\node_modules\formidable\lib\incoming_form.js:29:41)
    at UploadHandler.post (D:\vrem\moz\mosaico-master-link\node_modules\jquery-file-upload-middleware\lib\uploadhandler.js:68:20)
    at D:\vrem\moz\mosaico-master-link\node_modules\jquery-file-upload-middleware\lib\filehandler.js:48:25
    at Layer.handle [as handle_request] (D:\vrem\moz\mosaico-master-link\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\vrem\moz\mosaico-master-link\node_modules\express\lib\router\index.js:317:13)
    at D:\vrem\moz\mosaico-master-link\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\vrem\moz\mosaico-master-link\node_modules\express\lib\router\index.js:335:12)
    at next (D:\vrem\moz\mosaico-master-link\node_modules\express\lib\router\index.js:275:10)
    at urlencodedParser (D:\vrem\moz\mosaico-master-link\node_modules\body-parser\lib\types\urlencoded.js:100:7)
    at Layer.handle [as handle_request] (D:\vrem\moz\mosaico-master-link\node_modules\express\lib\router\layer.js:95:5)
`

Console after download one image:
https://prnt.sc/1w90h8e

If you need more information - tell me.

**Comment by bago** [comment]
Node keeps releasing breaking releases: try with an older node version, like 10.x.
